### ISSUE TITLE
Any plan to support 'non-std' build

### ISSUE THREAD

**Issue by jyao1** [aws/aws-lc-rs#114] opened 2023-04-27 01:47 UTC
### Problem:

It seems current aws-lc-rs does not support `no_std`. However, we are using [ring](https://github.com/briansmith/ring) which does support `no_std`.

Is there any plan to support `no_std` in the future ?

#### Relevant details

https://github.com/awslabs/aws-lc-rs/blob/main/aws-lc-rs/src/lib.rs#L93-L96

**Comment by justsmth** [comment] 2023-05-12 17:46
Thanks for the inquiry! We currently do not have plans to support a `no_std` build, but we're interested in understanding more about your use case.

We will leave this issue open for now to collect more feedback.

**Comment by cpu** [comment] 2023-07-14 14:24
Hi there. I accidentally filed a duplicate of this in #190.

> We will leave this issue open for now to collect more feedback.

Thanks for leaving this open for feedback. As mentioned in my duplicate, the [rustls](https://github.com/rustls/rustls) fork of [webpki](https://github.com/rustls/webpki) relies on *ring* for its cryptographic operations, as well as some DER parsing (mostly via *ring* helpers/re-exports of `untrusted`).  We would love to replace *ring* with `aws-lc-rs`, but we have [support for `no_std` builds](https://github.com/rustls/webpki/blob/3313270cb4064b5c3614f72020806f451edf7428/Cargo.toml#L64-L71) in that crate via feature flags.

We don't want to drop `no_std` support because one of [the development priorities](https://www.memorysafety.org/initiative/rustls/rustls-work-plan/) we have for the Rustls ecosystem is to support `no_std` throughout and so we'd be taking a step backwards by removing support in our `webpki` fork.

I think this is probably the primary blocker for us to adopt `aws-lc-rs` so it would be great if the project would be open to reconsidering the option of investing in `no_std` support.

**Comment by justsmth** [comment] 2024-01-16 14:27
Support for a `no_std` build is not on our current roadmap. We understand the value this would have for our customers and are open to considering it in the future.

**Closed by justsmth** 2024-01-16 14:27 UTC
Labels: enhancement

**Comment by theoparis** [comment] 2026-07-28 04:17
Is this something that could be considered if it were PR'd? I'm also interested in no_std support - the only other option I know of is rustls-rustcrypto and that performs worse obviously.

**Comment by justsmth** [comment] 2026-07-28 18:35
> Is this something that could be considered if it were PR'd? I'm also interested in no_std support - the only other option I know of is rustls-rustcrypto and that performs worse obviously.

Unfortunately, this isn't something that could be implemented as a standalone PR to `aws-lc-rs`.

AWS-LC (the C library providing our cryptographic operations) depends on libc and other OS facilities throughout -- threading primitives, OS-sourced entropy for the RNG, and heap allocation in both its implementation and its APIs. Removing the Rust crate's direct uses of `std` (e.g., switching to `no_std` + `alloc`) wouldn't make the underlying library usable in a typical bare-metal environment.

General `no_std` support would first require substantial changes in AWS-LC itself to remove or abstract those runtime dependencies. That work is not currently planned, and I'm not aware of a request for freestanding/no-OS support against AWS-LC itself. If this is something you'd like to pursue, opening a feature request on [aws/aws-lc](https://github.com/aws/aws-lc) would be a good starting point, since that's where the bulk of the work would be.
